### ISSUE TITLE
Editing online dictionary entries/Редактирование статей онлайн-словаря

### ISSUE THREAD

**Issue by HalanTul** [sakhatyla/SakhaTyla#23]
По окончанию редактирования одной статьи приходится каждый раз возвращаться в место входа, чтобы найти следующую статью для редактирования. Приходится пользоваться браузерной кнопкой возврата, терять время.
1. Хорошо бы на странице редактированной статьи разместить кнопку/ссылку "возврат к поиску" или само окошко поиска.
2. Можно ввести опцию для редактора: Показать страницы, помеченные значком Fuzzy. 
3. Можно выводить список таких статей с гиперссылками (скажем по 10), чтобы редактор открывал их попеременно в другой вкладке браузера.
4. Можно полностью переработать интерфейс редактирования, чтобы словарь показывал статьи в табличном виде в виде списка статей по алфавиту, по наличию значка Fuzzy, по другим параметрам (например по категориям). Нечто похожее на интерфейс Транслэйтвики.

**Comment by bacr** [comment]
Данные замечания относились к старом сайту. Пока закрою. Если еще актуально можно открыть и заново расписать список изменений.
